### ISSUE TITLE
I am concerned about the subject of this project

### ISSUE THREAD

**Issue by pjohnmeyer** [bngetich/liftoff-assignments#2]
I think you have the right size of project, and a good technology list, but I have a significant concern about your project.

HIPAA compliance is an _enormous_ issue for anything dealing with personal information in combination with medical information. There are people who make a career of doing nothing but advising and auditing software companies on this matter. I'm not sure it is a good idea to tackle a project in the medical information space for this class.

Is there a similarly-sized project you had in mind that can utilize the same technologies?

**Comment by bngetich** [comment]
Thanks for the feedback. I was not planning to use real data but just some dummy data. I do have another project in mind and will update the project outline shortly.

**Comment by pjohnmeyer** [comment]
Awesome. I don't want to discourage you from doing something you're excited about, but I think it is for the best.
