### ISSUE TITLE
P3: I cannot see your wireframes

### ISSUE THREAD

**Issue by pjohnmeyer** [bngetich/liftoff-assignments#4]
When I click on the [Moqup link](https://app.moqups.com/kimutaibryan@gmail.com/ly5Ah0NVjx/edit/page/a31fccfc8) I am presented with a login screen.

Per the assignment (emphasis mine)

> Regardless of how you create them, your wireframes should be clear and readable, and they should be **added as files** within your Git repository.

I understand there was some confusion about Moqup and the lack of ability to export; see https://liftoff-july-2018.slack.com/archives/CBTMFLWSJ/p1532715056000187 for some ideas.

**Comment by bngetich** [comment]
Updated link to wireframes

**Comment by pjohnmeyer** [comment]
👍
